server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ec2-50-16-108-41.compute-1.amazonaws.com:5432/d4sfqojo1nief5
    username: mpdykbexwikzom
    password: 587ed202bc90c2618d2aa7a077c1c2370cd3304f4ae3370617b8b758d8088808

jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  general-ddl: true
  hibernate:
    ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO-Santander